# Numpy
-----
## 03. 배열 연산과 함수
### 텍스트 파일 다루기
- savetxt : 배열을 텍스트 파일로 저장
- loadtxt : 텍스트 파일을 배열로 불러오기

In [1]:
import numpy as np

data = np.random.rand(5, 3)
print(data)

# 텍스트  파일로 저장 
# np.savetxt('data.txt', data)    # 공백으로 구분
np.savetxt('data.txt', data, delimiter=",")    # ,로 구분(CSV)
# 텍스트 파일을 배열로 불러오기
# load_data = np.loadtxt('data.txt')
load_data = np.loadtxt('data.txt', delimiter=",")
print(load_data)

[[0.50033598 0.34044757 0.87814625]
 [0.30762818 0.99591151 0.6950595 ]
 [0.75799083 0.72431608 0.79595751]
 [0.47876845 0.36421545 0.19054724]
 [0.02657211 0.31211473 0.36400569]]
[[0.50033598 0.34044757 0.87814625]
 [0.30762818 0.99591151 0.6950595 ]
 [0.75799083 0.72431608 0.79595751]
 [0.47876845 0.36421545 0.19054724]
 [0.02657211 0.31211473 0.36400569]]
[[0.50033598 0.34044757 0.87814625]
 [0.30762818 0.99591151 0.6950595 ]
 [0.75799083 0.72431608 0.79595751]
 [0.47876845 0.36421545 0.19054724]
 [0.02657211 0.31211473 0.36400569]]
[[0.50033598 0.34044757 0.87814625]
 [0.30762818 0.99591151 0.6950595 ]
 [0.75799083 0.72431608 0.79595751]
 [0.47876845 0.36421545 0.19054724]
 [0.02657211 0.31211473 0.36400569]]


### 바이너리 파일 다루기
- save : 배열을 바이너리 파일로 저장
    - 넘파이 배열의 확장자는 .npy
- load : 바이너리 파일을 배열로 불러오기

※ 바이너리 형식으로 데이터를 저장하고 불러오면 데이터 손실 없이 빠르게 처리할 수 있으므로, 크기가 크고 복잡한 데이터를 다룰 때 특히 유용

In [3]:
import numpy as np
import os
# 가상의 데이터 생성
data = np.random.rand(5, 3)
print("data :\n", data)
# 데이터를 바이너리 형식으로 저장
if not os.path.exists('./generated'):
    os.makedirs('./generated')
np.save('./generated/data', data)

load_data = np.load('./generated/data.npy')
print("load_data :\n", load_data)

data :
 [[8.03193186e-01 6.56170468e-02 6.05616014e-01]
 [6.92395281e-02 5.35221906e-01 9.02537668e-01]
 [6.86141310e-01 7.26248497e-01 4.25558722e-01]
 [3.11085015e-04 1.04291565e-01 3.59225478e-01]
 [6.05694326e-01 3.11717902e-01 6.05930356e-01]]
load_data :
 [[8.03193186e-01 6.56170468e-02 6.05616014e-01]
 [6.92395281e-02 5.35221906e-01 9.02537668e-01]
 [6.86141310e-01 7.26248497e-01 4.25558722e-01]
 [3.11085015e-04 1.04291565e-01 3.59225478e-01]
 [6.05694326e-01 3.11717902e-01 6.05930356e-01]]
data :
 [[8.03193186e-01 6.56170468e-02 6.05616014e-01]
 [6.92395281e-02 5.35221906e-01 9.02537668e-01]
 [6.86141310e-01 7.26248497e-01 4.25558722e-01]
 [3.11085015e-04 1.04291565e-01 3.59225478e-01]
 [6.05694326e-01 3.11717902e-01 6.05930356e-01]]
load_data :
 [[8.03193186e-01 6.56170468e-02 6.05616014e-01]
 [6.92395281e-02 5.35221906e-01 9.02537668e-01]
 [6.86141310e-01 7.26248497e-01 4.25558722e-01]
 [3.11085015e-04 1.04291565e-01 3.59225478e-01]
 [6.05694326e-01 3.11717902e-01 6.05930356e